### ISSUE TITLE
ENOENT: no such file or directory, stat 'C:\pinokio\api\artist.git\{{input.event[0]}}'

### ISSUE THREAD

**Issue by jerzysobski** [pinokiofactory/artist#1]
Receiving following error after an install and trying to run the app. Tried installing with and without Admin rights and receive same error.

**Comment by hacheraw** [comment]
Same problem

![image](https://github.com/user-attachments/assets/e80291e6-c790-44f7-8bfa-7a4856959eb7)

This is the URL that "Open Web UI" button opens: `http://localhost/api/artist.git/%7B%7Binput.event[0]%7D%7D`

Opening in Chrome shows this msg: `ENOENT: no such file or directory, stat 'C:\pinokio\api\artist.git\{{input.event[0]}}'`

**Comment by AkoZ** [comment]
exactly the same !! .. 
then terminal indicates:
Traceback (most recent call last):
  File "/media/USER/DedicatedDIR/APPS/Pinokio1/api/artist.git/app/injection_main_HF.py", line 5, in <module>
    import torch
  File "/media/USER/DedicatedDIR/APPS/Pinokio1/api/artist.git/app/env/lib/python3.10/site-packages/torch/__init__.py", line 239, in <module>
    from torch._C import *  # noqa: F403
ImportError: /lib/x86_64-linux-gnu/libcudnn.so.8: version **`libcudnn.so.8' not found** (required by /media/USER/DedicatedDIR/APPS/Pinokio1/api/artist.git/app/env/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
* So it means about installing `libcudnn.so.8 but i've the V9 in link .. how to not uninstall the V9 or make artist compatible ?
